name: Publish Chart
description: "Publish to gh-pages-backed chart repository"
inputs:
  dry_run:
    description: "Is this a dry run. If so no package will be published."
    required: true
  token:
    description: "The GitHub token used to upload artifacts to the published release"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: helm-repo

    - name: Determine chart version
      shell: bash
      id: version
      run: |
        version=$(helm show chart . | awk '/version/ { print $2 }')
        echo "CHART_VERSION=$version" >> "$GITHUB_OUTPUT"
        echo "ARTIFACT=ld-relay-$version.tgz" >> "$GITHUB_OUTPUT"

    - name: Package the helm chart
      shell: bash
      run: |
        mkdir -p new-chart
        helm package -d new-chart .

    - name: Generate updated index.yaml
      shell: bash
      run: helm repo index new-chart --url https://launchdarkly.github.io/ld-relay-helm --merge helm-repo/index.yaml

    - name: Move files into publishable directory
      shell: bash
      run: mv new-chart/${{ steps.version.outputs.ARTIFACT }} new-chart/index.yaml helm-repo
      run: mv helm-repo/*tgz new-chart/

    - name: Publish to GitHub pages
      if: ${{ inputs.dry_run == 'false' }}
      uses: launchdarkly/gh-actions/actions/publish-pages@publish-pages-v1.0.2
      with:
        docs_path: new-chart
        github_token: ${{ inputs.token }}

    - name: Attach published chart to release
      if: ${{ inputs.dry_run == 'false' }}
      shell: bash
      run: gh release upload ${{ steps.version.outputs.CHART_VERSION }} helm-repo/${{ steps.version.outputs.ARTIFACT }} --clobber
      env:
        GH_TOKEN: ${{ inputs.token }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push chart to GHCR
      run: |
        mkdir -p ld-relay
        helm package -d ld-relay .
        helm push ld-relay-*.tgz oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts    
