{{- if .Values.httpRoute.enabled -}}
{{- $fullName := include "ld-relay.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ include "ld-relay.namespace" . }}
  labels:
    {{- include "ld-relay.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httpRoute.parentRefs }}
  parentRefs:
    {{- range . }}
    - name: {{ .name }}
      {{- with .namespace }}
      namespace: {{ . }}
      {{- end }}
      {{- with .sectionName }}
      sectionName: {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- range . }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.httpRoute.rules }}
    - {{- with .matches }}
      matches:
        {{- range . }}
        - path:
            type: {{ .path.type }}
            value: {{ .path.value }}
        {{- end }}
      {{- end }}
      backendRefs:
        - name: {{ $fullName }}
          port: {{ .port }}
    {{- end }}
{{- end }}
