apiVersion: v1
kind: Service
metadata:
  name: {{ include "ld-relay-helm.fullname" . }}
  labels:
    {{- include "ld-relay-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
     - port: {{ .port }}
       protocol: {{ .protocol }}
       name: {{ .name }}
       targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    {{- include "ld-relay-helm.selectorLabels" . | nindent 4 }}
